Repository lumium-technologies/lumium, pull requests merged in 2022-11, with the labels that each got.

#115 ops(clang): install clang toolchain
  git-conventional-commits.json
  lumium-renderer/Cargo.toml
  lumium-renderer/src/lib.rs
  lumium-renderer/tests/web.rs
  lumium-space/.gitignore
  lumium-space/package.json
  lumium-space/scripts/build-renderer.sh
  lumium-space/scripts/docker-entry.sh
  lumium-space/scripts/rust-toolchain.sh
  lumium-space/scripts/toolchain.sh
  package.json
  scripts/reduce-slug-size-heroku.sh
  yarn.lock
Labels: dependencies, infrastructure

#119 ops(actions):add heroku labeler
  .github/workflows/heroku-review-app-management.yml
Labels: enhancement, infrastructure

#122 fix:loginflow with keyboard
  lumium-space/pages/auth/signin.tsx
  lumium-space/pages/auth/signup.tsx
Labels: bug, enhancement

#113 feat:add encryption and decryption capabilities for content
  .github/workflows/nxcloud.yml
  git-conventional-commits.json
  lumium-renderer/.env.test
  lumium-renderer/Cargo.toml
  lumium-renderer/src/lib.rs
  lumium-renderer/tests/web.rs
  lumium-space/.gitignore
  lumium-space/package.json
  lumium-space/scripts/build-renderer.sh
  lumium-space/scripts/docker-entry.sh
  lumium-space/scripts/rust-toolchain.sh
  lumium-space/scripts/toolchain.sh
  nx.json
  package.json
  scripts/build.sh
  scripts/reduce-slug-size-heroku.sh
  yarn.lock
Labels: enhancement, feature, security

#126 ops(actions):fix duplicate execution of workflows
  .github/workflows/api-unit.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/lumium-renderer.yml
  .github/workflows/space-e2e.yml
  .github/workflows/space-unit.yml
Labels: enhancement, good first issue, infrastructure

#127 feat:add nonces to workspace create payload
  lumium-api/src/controllers/workspace/index.ts
  lumium-api/src/entity/E2EKeyVariant.ts
  lumium-api/src/migration/1668208914317-nonces.ts
  lumium-api/src/routes/v1/secure/workspace/workspace.spec.ts
  types/api/v1/dto/request/E2EKeyVariantCreateDTO.ts
Labels: enhancement, security

#131 fix:cors
  lumium-api/.env.review
  lumium-api/src/app.ts
Labels: bug, security

#136 fix:api unit tests
  lumium-api/src/routes/v1/secure/page/page.spec.ts
  lumium-api/test/jest-teardown-globals.ts
  lumium-api/test/jest.config.js
Labels: bug, infrastructure

#137 feat:redirect to lumium domains
  lumium-api/src/app.ts
  lumium-api/src/routes/v1/secure/workspace/workspace.spec.ts
  lumium-space/pages/_middleware.tsx
Labels: bug, security

#138 fix: remove authenticator from reset page
  lumium-space/pages/auth/reset-password.tsx
Labels: bug, good first issue, security

#142 ops(docker):add dockerfile for space
  lumium-api/Dockerfile
  lumium-space/Dockerfile
  lumium-space/package.json
  scripts/dockerize.sh
  yarn.lock
Labels: enhancement, good first issue, infrastructure
