Repository lumium-technologies/lumium, pull requests merged in 2022-12, with the labels that each got.

#159 fix:readd middleware, escape sequence
  lumium-space/middleware.ts
  lumium-space/pages/auth/[[...path]].tsx
Labels: bug, good first issue, infrastructure

#161 add cypress tests
  lumium-space/cypress/integration/auth.spec.ts
  lumium-space/cypress/integration/auth_reset-password.spec.ts
  lumium-space/cypress/integration/auth_signin.spec.ts
  lumium-space/cypress/integration/auth_signup.spec.ts
  lumium-space/cypress/integration/root.spec.ts
  lumium-space/cypress/support/commands.ts
  lumium-space/cypress/support/index.ts
  lumium-space/cypress/support/makeid.ts
  lumium-space/cypress/tsconfig.json
  lumium-space/pages/auth/reset-password.tsx
  lumium-space/pages/auth/signin.tsx
  lumium-space/pages/auth/signup.tsx
  lumium-space/src/sections/landing/NavBar.tsx
Labels: enhancement, cypress

#168 feat(renderer):hash password to 256 bits as key
  lumium-renderer/Cargo.toml
  lumium-renderer/js/download.js
  lumium-renderer/src/lib.rs
Labels: enhancement, security

#174 ops(cloudflare):fix dns record removal
  app.json
  scripts/remove-cloudflare-dns.sh
Labels: bug, enhancement, infrastructure

#177 refactor(renderer):restructure
  lumium-renderer/.cargo/config.toml
  lumium-renderer/src/crypto.rs
  lumium-renderer/src/lib.rs
  lumium-renderer/tests/web.rs
Labels: enhancement, security

#178 feat(api):map to dtos
  lumium-api/src/controllers/workspace/index.ts
  lumium-api/src/entity/AbstractEntity.ts
  lumium-api/src/entity/ContentElement.ts
  lumium-api/src/entity/Email.ts
  lumium-api/src/entity/Page.ts
  lumium-api/src/entity/PageContent.ts
  lumium-api/src/entity/User.ts
  lumium-api/src/entity/Workspace.ts
  lumium-api/src/entity/WorkspacePreference.ts
  lumium-api/src/routes/v1/index.ts
  types/api/v1/dto/entity/PageContentDTO.ts
Labels: enhancement

#165 test: add spaces new tests
  lumium-space/.gitignore
  lumium-space/cypress/e2e/auth_reset-password.cy.ts
  lumium-space/cypress/e2e/auth_signin.cy.ts
  lumium-space/cypress/e2e/auth_signup.cy.ts
  lumium-space/cypress/e2e/spaces_create.cy.ts
  lumium-space/cypress/e2e/spaces_join.cy.ts
  lumium-space/cypress/e2e/spaces_new.cy.ts
  lumium-space/cypress/support/commands.ts
  lumium-space/pages/auth/reset-password.tsx
  lumium-space/pages/auth/signin.tsx
  lumium-space/pages/auth/signup.tsx
  lumium-space/pages/spaces/create.tsx
  lumium-space/pages/spaces/join.tsx
  lumium-space/pages/spaces/new.tsx
  lumium-space/src/components/security/AuthenticatorAuth.tsx
  lumium-space/src/hooks/api/useApi.ts
Labels: cypress

#182 ops(actions):auto-add issues and PRs to project
  .github/workflows/issues-to-project.yml
  .github/workflows/prs-to-project.yml
Labels: infrastructure

#186 ops(release):set version in all package.json files
  .github/workflows/release.yml
  lumium-api/package.json
  lumium-space/package.json
Labels: documentation, enhancement, infrastructure

#188 merge:update master
  .github/workflows/issues-to-project.yml
  .github/workflows/prs-to-project.yml
  .github/workflows/release.yml
  .gitignore
  README.md
  app.json
  lumium-api/package.json
  lumium-api/src/controllers/workspace/index.ts
  lumium-api/src/entity/AbstractEntity.ts
  lumium-api/src/entity/ContentElement.ts
  lumium-api/src/entity/Email.ts
  lumium-api/src/entity/Page.ts
  lumium-api/src/entity/PageContent.ts
  lumium-api/src/entity/User.ts
  lumium-api/src/entity/Workspace.ts
  lumium-api/src/entity/WorkspacePreference.ts
  lumium-api/src/migration/1671050918560-keys.ts
  lumium-api/src/routes/v1/index.ts
  lumium-renderer/.cargo/config.toml
  lumium-renderer/Cargo.toml
  lumium-renderer/js/download.js
  lumium-renderer/src/crypto.rs
  lumium-renderer/src/lib.rs
  lumium-renderer/tests/web.rs
  lumium-space/.gitignore
  lumium-space/cypress.config.ts
  lumium-space/cypress.json
  lumium-space/cypress/e2e/auth.cy.ts
  lumium-space/cypress/e2e/auth_reset-password.cy.ts
  lumium-space/cypress/e2e/auth_signin.cy.ts
  lumium-space/cypress/e2e/auth_signup.cy.ts
  lumium-space/cypress/e2e/root.cy.ts
  lumium-space/cypress/e2e/spaces_create.cy.ts
  lumium-space/cypress/e2e/spaces_join.cy.ts
  lumium-space/cypress/e2e/spaces_new.cy.ts
  lumium-space/cypress/integration/auth_reset-password.spec.ts
  lumium-space/cypress/integration/auth_signin.spec.ts
  lumium-space/cypress/integration/auth_signup.spec.ts
  lumium-space/cypress/support/commands.ts
  lumium-space/cypress/support/e2e.ts
  lumium-space/cypress/support/index.ts
  lumium-space/next.config.js
  lumium-space/package.json
  lumium-space/pages/auth/reset-password.tsx
  lumium-space/pages/auth/signin.tsx
  lumium-space/pages/auth/signup.tsx
  lumium-space/pages/spaces/create.tsx
  lumium-space/pages/spaces/join.tsx
  lumium-space/pages/spaces/new.tsx
  lumium-space/src/components/security/AuthenticatorAuth.tsx
  lumium-space/src/hooks/api/useApi.ts
  lumium-space/src/sections/landing/Footer.tsx
  scripts/remove-cloudflare-dns.sh
  types/api/v1/dto/entity/PageContentDTO.ts
  yarn.lock
Labels: prod-release

#189 deps(space):add tsparticles dependency
  lumium-space/package.json
  yarn.lock
Labels: dependencies

#191 ops(github):migrate project to org
  .github/workflows/issues-to-project.yml
  .github/workflows/prs-to-project.yml
  git-conventional-commits.json
Labels: enhancement, infrastructure

#194 test: add redirection tests
  lumium-space/cypress/e2e/redirection.cy.ts
  lumium-space/pages/auth/reset-password.tsx
Labels: cypress

#195 refactor(renderer):extract renderer module
  lumium-renderer/Cargo.toml
  lumium-renderer/src/lib.rs
  lumium-renderer/src/render.rs
  lumium-renderer/src/utils.rs
Labels: enhancement

#180 feat(api):add `name` attr to pages and workspaces
  lumium-api/src/controllers/workspace/index.ts
  lumium-api/src/entity/E2EKey.ts
  lumium-api/src/entity/E2EKeyVariant.ts
  lumium-api/src/entity/Page.ts
  lumium-api/src/entity/PageContent.ts
  lumium-api/src/entity/Workspace.ts
  lumium-api/src/migration/1671052377954-workspace-page-name.ts
  lumium-api/src/routes/v1/index.ts
  lumium-api/src/routes/v1/secure/user/user.spec.ts
  lumium-api/src/routes/v1/secure/workspace/index.ts
  lumium-api/src/routes/v1/secure/workspace/workspace.spec.ts
  lumium-renderer/Cargo.toml
  lumium-renderer/src/lib.rs
  lumium-renderer/src/render.rs
  lumium-renderer/src/utils.rs
  lumium-space/pages/spaces/create.tsx
  types/api/index.ts
  types/api/v1/dto/entity/E2EKeyDTO.ts
  types/api/v1/dto/entity/E2EKeyVariantDTO.ts
  types/api/v1/dto/entity/PageDTO.ts
  types/api/v1/dto/entity/WorkspaceDTO.ts
  types/api/v1/dto/entity/index.ts
  types/api/v1/dto/index.ts
  types/api/v1/dto/request/WorkspaceCreateDTO.ts
  types/api/v1/dto/request/WorkspaceUpdateDTO.ts
  types/api/v1/dto/request/index.ts
  types/api/v1/index.ts
Labels: enhancement, feature

#198 merge:update master
  lumium-api/src/controllers/workspace/index.ts
  lumium-api/src/entity/E2EKey.ts
  lumium-api/src/entity/E2EKeyVariant.ts
  lumium-api/src/entity/Page.ts
  lumium-api/src/entity/PageContent.ts
  lumium-api/src/entity/Workspace.ts
  lumium-api/src/migration/1671052377954-workspace-page-name.ts
  lumium-api/src/routes/v1/index.ts
  lumium-api/src/routes/v1/secure/user/user.spec.ts
  lumium-api/src/routes/v1/secure/workspace/index.ts
  lumium-api/src/routes/v1/secure/workspace/workspace.spec.ts
  lumium-renderer/Cargo.toml
  lumium-renderer/src/lib.rs
  lumium-renderer/src/render.rs
  lumium-renderer/src/utils.rs
  lumium-space/cypress/e2e/redirection.cy.ts
  lumium-space/pages/auth/reset-password.tsx
  lumium-space/pages/spaces/create.tsx
  types/api/index.ts
  types/api/v1/dto/entity/E2EKeyDTO.ts
  types/api/v1/dto/entity/E2EKeyVariantDTO.ts
  types/api/v1/dto/entity/PageDTO.ts
  types/api/v1/dto/entity/WorkspaceDTO.ts
  types/api/v1/dto/entity/index.ts
  types/api/v1/dto/index.ts
  types/api/v1/dto/request/WorkspaceCreateDTO.ts
  types/api/v1/dto/request/WorkspaceUpdateDTO.ts
  types/api/v1/dto/request/index.ts
  types/api/v1/index.ts
Labels: prod-release

#200 refactor(landing-page):add logo, refactor
  README.md
  lumium-api/package.json
  lumium-space/package.json
  lumium-space/pages/auth/reset-password.tsx
  lumium-space/pages/auth/signin.tsx
  lumium-space/pages/auth/signup.tsx
  lumium-space/src/components/security/AuthenticatorAuth.tsx
  lumium-space/src/hooks/api/useUserInfo.ts
  lumium-space/src/sections/landing/CallToAction.tsx
  lumium-space/src/sections/landing/Footer.tsx
  lumium-space/src/sections/landing/NavBar.tsx
  package.json
Labels: enhancement

#203 release:update master
  lumium-space/pages/auth/reset-password.tsx
  lumium-space/pages/auth/signin.tsx
  lumium-space/pages/auth/signup.tsx
Labels: prod-release

#205 release:update master
  lumium-space/src/sections/landing/NavBar.tsx
Labels: prod-release

#210 add own authentication to frontend
  lumium-api/package.json
  lumium-api/src/controllers/index.ts
  lumium-space/config/appInfo.ts
  lumium-space/config/frontendConfig.tsx
  lumium-space/package.json
  lumium-space/pages/_app.tsx
  lumium-space/pages/account/index.tsx
  lumium-space/pages/auth/signin.tsx
  lumium-space/pages/auth/signup.tsx
  lumium-space/src/components/security/Authenticator.tsx
  lumium-space/src/hooks/api/index.ts
  lumium-space/src/hooks/api/useApi.ts
  yarn.lock
Labels: feature, security

#209 feat(auth):generate and verify own JWTs
  lumium-api/.env.development
  lumium-api/.env.test
  lumium-api/bin/generate-secret.js
  lumium-api/package.json
  lumium-api/src/app.ts
  lumium-api/src/controllers/auth.ts
  lumium-api/src/controllers/index.ts
  lumium-api/src/controllers/page.ts
  lumium-api/src/controllers/user.ts
  lumium-api/src/controllers/user/index.ts
  lumium-api/src/controllers/workspace.ts
  lumium-api/src/crypto.ts
  lumium-api/src/entity/AuthenticationInformation.ts
  lumium-api/src/entity/BlacklistedToken.ts
  lumium-api/src/entity/User.ts
  lumium-api/src/migration/1671442474951-initial.ts
  lumium-api/src/routes/v1/index.ts
  lumium-api/src/routes/v1/public/auth.ts
  lumium-api/src/routes/v1/public/index.ts
  lumium-api/src/routes/v1/secure/auth.ts
  lumium-api/src/routes/v1/secure/index.ts
  lumium-api/src/routes/v1/secure/page.ts
  lumium-api/src/routes/v1/secure/user.spec.ts
  lumium-api/src/routes/v1/secure/user.ts
  lumium-api/src/routes/v1/secure/workspace.spec.ts
  lumium-api/src/routes/v1/secure/workspace.ts
  lumium-api/test/jest.setup.ts
  lumium-renderer/Cargo.toml
  lumium-renderer/src/lib.rs
  lumium-space/config/appInfo.ts
  lumium-space/config/frontendConfig.tsx
  lumium-space/cypress/e2e/auth_reset-password.cy.ts
  lumium-space/cypress/e2e/auth_signin.cy.ts
  lumium-space/cypress/e2e/auth_signup.cy.ts
  lumium-space/cypress/support/commands.ts
  lumium-space/package.json
  lumium-space/pages/_app.tsx
  lumium-space/pages/account/index.tsx
  lumium-space/pages/auth/signin.tsx
  lumium-space/pages/auth/signup.tsx
  lumium-space/src/components/security/Authenticator.tsx
  lumium-space/src/hooks/api/index.ts
  lumium-space/src/hooks/api/useApi.ts
  routes/api/v1/index.ts
  routes/api/v1/public/auth.ts
  routes/api/v1/public/index.ts
  routes/api/v1/secure/auth.ts
  routes/api/v1/secure/index.ts
  types/api/index.ts
  types/api/v1/dto/index.ts
  types/api/v1/dto/request/UserAuthDTO.ts
  types/api/v1/dto/request/index.ts
  types/api/v1/dto/response/ReasonDTO.ts
  types/api/v1/dto/response/index.ts
  types/api/v1/index.ts
  types/index.ts
  yarn.lock
Labels: feature, security

#221 release:update master
  lumium-api/src/controllers/auth.ts
Labels: prod-release

#219 add profile menu to landingpage
  lumium-space/pages/[workspaceId]/index.tsx
  lumium-space/pages/auth/signin.tsx
  lumium-space/pages/spaces/[[...path]].tsx
  lumium-space/src/hooks/api/index.ts
  lumium-space/src/hooks/api/useApi.ts
  lumium-space/src/hooks/api/useUserInfo.ts
  lumium-space/src/hooks/api/useWorkspace.ts
  lumium-space/src/hooks/index.ts
  lumium-space/src/sections/landing/NavBar.tsx
Labels: enhancement, feature

#222 fix(e2e):save e2e key variants correctly on workspace creation
  lumium-api/src/controllers/workspace.ts
  lumium-api/src/entity/E2EKey.ts
  lumium-api/src/entity/E2EKeyVariant.ts
  lumium-api/src/entity/Workspace.ts
  lumium-api/src/migration/1671487559078-test.ts
Labels: bug, security

#226 feat(space):add transitions
  lumium-space/package.json
  lumium-space/pages/_app.tsx
  lumium-space/src/components/transitions/PageTransition.tsx
  lumium-space/src/components/transitions/index.ts
  lumium-space/src/sections/landing/NavBar.tsx
  lumium-space/src/styles/transition.css
  yarn.lock
Labels: enhancement, feature

#227 release:pull develop
  lumium-api/package.json
  lumium-api/src/controllers/workspace.ts
  lumium-api/src/entity/E2EKey.ts
  lumium-api/src/entity/E2EKeyVariant.ts
  lumium-api/src/entity/Workspace.ts
  lumium-api/src/migration/1671487559078-test.ts
  lumium-space/package.json
  lumium-space/pages/[workspaceId]/index.tsx
  lumium-space/pages/_app.tsx
  lumium-space/pages/auth/signin.tsx
  lumium-space/pages/spaces/[[...path]].tsx
  lumium-space/src/components/transitions/PageTransition.tsx
  lumium-space/src/components/transitions/index.ts
  lumium-space/src/hooks/api/index.ts
  lumium-space/src/hooks/api/useApi.ts
  lumium-space/src/hooks/api/useUserInfo.ts
  lumium-space/src/hooks/api/useWorkspace.ts
  lumium-space/src/hooks/index.ts
  lumium-space/src/sections/landing/NavBar.tsx
  lumium-space/src/styles/transition.css
  yarn.lock
Labels: prod-release

#233 refactor: remove overview
  lumium-space/cypress/e2e/redirection.cy.ts
  lumium-space/cypress/e2e/spaces_overview.cy.ts
  lumium-space/cypress/support/commands.ts
  lumium-space/pages/[workspaceId]/index.tsx
  lumium-space/pages/auth/signin.tsx
  lumium-space/pages/auth/signup.tsx
  lumium-space/pages/spaces/[[...path]].tsx
  lumium-space/pages/spaces/overview.tsx
  routes/space/index.ts
Labels: enhancement

#235 feat(e2e):sync page content
  lumium-renderer/Cargo.toml
  lumium-renderer/src/crypto.rs
  lumium-renderer/src/dtos.rs
  lumium-renderer/src/lib.rs
  lumium-renderer/src/render.rs
  lumium-renderer/tests/web.rs
  lumium-space/pages/[workspaceId]/[[...pageId]].tsx
  lumium-space/pages/[workspaceId]/[pageId].tsx
Labels: enhancement, feature, security

#236 release:pull develop
  lumium-renderer/Cargo.toml
  lumium-renderer/src/crypto.rs
  lumium-renderer/src/dtos.rs
  lumium-renderer/src/lib.rs
  lumium-renderer/src/render.rs
  lumium-renderer/tests/web.rs
  lumium-space/cypress/e2e/redirection.cy.ts
  lumium-space/cypress/e2e/spaces_overview.cy.ts
  lumium-space/cypress/support/commands.ts
  lumium-space/pages/[workspaceId]/[[...pageId]].tsx
  lumium-space/pages/[workspaceId]/[pageId].tsx
  lumium-space/pages/auth/signin.tsx
  lumium-space/pages/auth/signup.tsx
  lumium-space/pages/spaces/[[...path]].tsx
  lumium-space/pages/spaces/overview.tsx
  routes/space/index.ts
Labels: prod-release

#237 release:pull develop
  lumium-api/src/controllers/user.ts
  lumium-api/src/data-source.ts
Labels: prod-release
