Repository lumium-technologies/lumium, pull requests merged in 2022-10, with the labels that each got.

#84 feat: refactor constants
  lumium-api/routes
  lumium-api/src/app.ts
  lumium-api/src/routes/v1/public/index.ts
  lumium-api/src/routes/v1/secure/index.ts
  lumium-api/src/routes/v1/secure/user/index.ts
  lumium-api/src/routes/v1/secure/workspace/index.ts
  lumium-space/pages/account/[[...path]].tsx
  lumium-space/pages/index.tsx
  lumium-space/pages/workspace/[workspaceUUID]/[pageUUID].tsx
  lumium-space/pages/workspace/[workspaceUUID]/index.tsx
  lumium-space/pages/workspace/index.ts
  lumium-space/routes
  lumium-space/tsconfig.json
  routes/api/v1/index.ts
  routes/api/v1/secure/index.ts
  routes/api/v1/secure/user.ts
  routes/api/v1/secure/workspace.ts
  routes/space/index.ts
Labels: enhancement, feature

#45 feat(login): replace default login widget
  lumium-api/src/controllers/user/index.ts
  lumium-space/cypress/integration/auth-page.spec.ts
  lumium-space/cypress/integration/landing-page.spec.ts
  lumium-space/cypress/integration/manage-spaces-page.spec.ts
  lumium-space/cypress/integration/page.spec.ts
  lumium-space/cypress/support/commands.ts
  lumium-space/cypress/support/index.ts
  lumium-space/next.config.js
  lumium-space/pages/[workspaceUUID]/[pageUUID].tsx
  lumium-space/pages/[workspaceUUID]/index.tsx
  lumium-space/pages/account/[[...path]].tsx
  lumium-space/pages/auth/[[...path]].tsx
  lumium-space/pages/auth/reset-password.tsx
  lumium-space/pages/auth/signin.tsx
  lumium-space/pages/auth/signup.tsx
  lumium-space/pages/auth/verify-email.tsx
  lumium-space/pages/index.tsx
  lumium-space/pages/spaces/new.tsx
  lumium-space/pages/workspace/index.ts
  lumium-space/src/components/headers/Header.tsx
  lumium-space/src/components/headers/ProfileMenu.tsx
  lumium-space/src/components/headers/index.tsx
  lumium-space/src/components/heros/Hero.tsx
  lumium-space/src/components/heros/index.tsx
  lumium-space/src/hooks/security/authentication/useLoginStatus.ts
  lumium-space/src/security/authentication/authenticators/Authenticator.tsx
  routes/space/index.ts
  yarn.lock
Labels: enhancement, feature

#105 feat: add delete workspace endpoint
  lumium-api/src/controllers/workspace/index.ts
  lumium-api/src/entity/Audit.ts
  lumium-api/src/migration/1666191331711-delete-workspace.ts
  lumium-api/src/routes/v1/secure/workspace/index.ts
  lumium-api/src/routes/v1/secure/workspace/workspace.spec.ts
  routes/api/v1/index.ts
  routes/api/v1/secure/index.ts
  routes/api/v1/secure/workspace.ts
Labels: enhancement, feature

#103 refactor: change http methods from post to put
  lumium-api/src/routes/v1/secure/workspace/index.ts
  lumium-api/src/routes/v1/secure/workspace/workspace.spec.ts
  routes/api/v1/index.ts
  routes/api/v1/secure/index.ts
  routes/api/v1/secure/workspace.ts
Labels: bug, enhancement

#107 feat: add patch for workspace
  lumium-api/src/app.ts
  lumium-api/src/controllers/workspace/index.ts
  lumium-api/src/entity/Audit.ts
  lumium-api/src/routes/v1/index.ts
  lumium-api/src/routes/v1/secure/workspace/index.ts
  lumium-api/src/routes/v1/secure/workspace/workspace.spec.ts
  routes/api/v1/index.ts
  routes/api/v1/secure/index.ts
  routes/api/v1/secure/workspace.ts
  types/api/index.ts
  types/api/v1/dto/index.ts
  types/api/v1/dto/request/WorkspaceUpdateDTO.ts
  types/api/v1/dto/request/index.ts
  types/api/v1/index.ts
  types/index.ts
Labels: enhancement, feature

#111 feat: add get endpoint for page
  lumium-api/src/controllers/page/index.ts
  lumium-api/src/controllers/user/index.ts
  lumium-api/src/controllers/workspace/index.ts
  lumium-api/src/entity/Audit.ts
  lumium-api/src/routes/v1/secure/index.ts
  lumium-api/src/routes/v1/secure/page/index.ts
  lumium-api/src/routes/v1/secure/page/page.spec.ts
  lumium-api/src/routes/v1/secure/workspace/index.ts
  routes/api/v1/index.ts
  routes/api/v1/secure/index.ts
  routes/api/v1/secure/page.ts
  routes/api/v1/secure/workspace.ts
  yarn.lock
Labels: bug, enhancement, feature

#109 feat: add workspace post endpoint
  lumium-api/src/controllers/workspace/index.ts
  lumium-api/src/entity/Audit.ts
  lumium-api/src/routes/v1/secure/workspace/index.ts
  routes/api/v1/index.ts
  routes/api/v1/secure/index.ts
  routes/api/v1/secure/workspace.ts
  yarn.lock
Labels: enhancement, feature
