Repository lumium-technologies/lumium, pull requests merged in 2023-01, with the labels that each got.

#238 release:pull develop
  lumium-space/pages/[workspaceId]/[[...pageId]].tsx
Labels: prod-release

#243 feat: add closeable sidebar
  lumium-space/pages/[workspaceId]/[[...pageId]].tsx
  lumium-space/pages/account.tsx
  lumium-space/pages/auth/signin.tsx
  lumium-space/pages/spaces/create.tsx
  lumium-space/src/components/forms/CreateWorkspace.tsx
  lumium-space/src/sections/workspace/NavBar.tsx
  lumium-space/src/sections/workspace/SideBar.tsx
Labels: enhancement

#244 release:pull develop
  lumium-space/pages/[workspaceId]/[[...pageId]].tsx
  lumium-space/pages/account.tsx
  lumium-space/pages/auth/signin.tsx
  lumium-space/pages/spaces/create.tsx
  lumium-space/src/components/forms/CreateWorkspace.tsx
  lumium-space/src/sections/workspace/NavBar.tsx
  lumium-space/src/sections/workspace/SideBar.tsx
Labels: prod-release

#246 add working buttons
  lumium-space/pages/[workspaceId]/[[...pageId]].tsx
  lumium-space/pages/index.tsx
  lumium-space/pages/spaces/create.tsx
  lumium-space/src/sections/landing/NavBar.tsx
  lumium-space/src/sections/workspace/NavBar.tsx
  lumium-space/src/sections/workspace/SideBar.tsx
Labels: enhancement

#250 release:pull develop
  lumium-api/src/entity/Address.ts
  lumium-api/src/entity/Audit.ts
  lumium-api/src/entity/BlacklistedToken.ts
  lumium-api/src/entity/UserPreference.ts
  lumium-api/src/entity/WorkspacePreference.ts
  lumium-space/pages/[workspaceId]/[[...pageId]].tsx
  lumium-space/pages/index.tsx
  lumium-space/pages/spaces/create.tsx
  lumium-space/src/sections/landing/NavBar.tsx
  lumium-space/src/sections/workspace/NavBar.tsx
  lumium-space/src/sections/workspace/SideBar.tsx
  yarn.lock
Labels: prod-release

#251 release:pull develop
  lumium-space/pages/[workspaceId]/[[...pageId]].tsx
  lumium-space/pages/account.tsx
  lumium-space/pages/auth/reset-password.tsx
  lumium-space/pages/auth/signin.tsx
  lumium-space/pages/auth/signup.tsx
  lumium-space/pages/index.tsx
  lumium-space/pages/spaces/[[...path]].tsx
  lumium-space/pages/spaces/create.tsx
  lumium-space/src/components/notifications/Error.tsx
  lumium-space/src/components/notifications/index.tsx
  lumium-space/src/components/other/AuthBox.tsx
  lumium-space/src/components/other/CreateWorkspace.tsx
  lumium-space/src/components/other/PageTitle.tsx
  lumium-space/src/components/other/index.ts
  lumium-space/src/sections/landing/CallToAction.tsx
  lumium-space/src/sections/landing/Footer.tsx
  lumium-space/src/sections/landing/NavBar.tsx
  lumium-space/src/sections/landing/index.ts
  lumium-space/src/sections/workspace/NavBar.tsx
  lumium-space/src/sections/workspace/SideBar.tsx
  lumium-space/src/sections/workspace/index.ts
Labels: prod-release

#253 release:pull develop
  lumium-space/package.json
  lumium-space/pages/[workspaceId]/[[...pageId]].tsx
  lumium-space/src/sections/workspace/NavBar.tsx
  lumium-space/src/sections/workspace/SideBar.tsx
  yarn.lock
Labels: prod-release

#255 release:pull develop
  lumium-space/cypress/support/commands.ts
  lumium-space/pages/[workspaceId]/[[...pageId]].tsx
  lumium-space/pages/account.tsx
  lumium-space/pages/auth/[[...path]].tsx
  lumium-space/pages/auth/reset-password.tsx
  lumium-space/pages/auth/signin.tsx
  lumium-space/pages/auth/signup.tsx
  lumium-space/pages/index.tsx
  lumium-space/pages/spaces/create.tsx
  lumium-space/src/components/other/AuthBox.tsx
  lumium-space/src/components/other/CreateWorkspace.tsx
  lumium-space/src/components/other/WorkspaceSideBarButton.tsx
  lumium-space/src/components/other/index.ts
  lumium-space/src/definitions/constants.ts
  lumium-space/src/sections/account/NavBar.tsx
  lumium-space/src/sections/account/SideBar.tsx
  lumium-space/src/sections/account/index.ts
  lumium-space/src/sections/landing/Footer.tsx
  lumium-space/src/sections/landing/NavBar.tsx
  lumium-space/src/sections/workspace/NavBar.tsx
  lumium-space/src/sections/workspace/SideBar.tsx
  routes/space/index.ts
Labels: prod-release

#257 add widgetcentered, store pinned in localstorage
  lumium-space/pages/[workspaceId]/[[...pageId]].tsx
  lumium-space/pages/account.tsx
  lumium-space/pages/auth/reset-password.tsx
  lumium-space/pages/auth/signin.tsx
  lumium-space/pages/auth/signup.tsx
  lumium-space/src/components/other/AuthBox.tsx
  lumium-space/src/components/other/CreateWorkspace.tsx
  lumium-space/src/components/other/WidgetCentered.tsx
  lumium-space/src/components/other/index.ts
  lumium-space/src/definitions/chakra/theme/styles.ts
  lumium-space/src/definitions/constants.ts
  lumium-space/src/sections/account/NavBar.tsx
  lumium-space/src/sections/workspace/SideBar.tsx
Labels: enhancement

#224 feat(page):crud for pages
  lumium-api/src/controllers/page.ts
  lumium-api/src/controllers/workspace.ts
  lumium-api/src/entity/Page.ts
  lumium-api/src/routes/v1/index.ts
  lumium-api/src/routes/v1/secure/page.ts
  lumium-api/src/routes/v1/secure/workspace.spec.ts
  lumium-api/src/routes/v1/secure/workspace.ts
  routes/api/v1/secure/page.ts
  routes/api/v1/secure/workspace.ts
  types/api/index.ts
  types/api/v1/dto/index.ts
  types/api/v1/dto/request/PageCreateDTO.ts
  types/api/v1/dto/request/PageUpdateDTO.ts
  types/api/v1/dto/request/index.ts
  types/api/v1/index.ts
  types/index.ts
Labels: feature

#265 feat(api):add secret endpoint for workspace password encryption secrets
  lumium-api/src/controllers/workspace.ts
  lumium-api/src/entity/Workspace.ts
  lumium-api/src/entity/WorkspaceSecret.ts
  lumium-api/src/routes/v1/index.ts
  lumium-api/src/routes/v1/secure/workspace.ts
  routes/api/v1/secure/workspace.ts
  types/api/v1/response/WorkspaceSecretDTO.ts
Labels: feature

#268 refactor(build):introduce `make`
  .github/workflows/codeql-analysis.yml
  .github/workflows/lumium-renderer.yml
  .github/workflows/space-e2e.yml
  .github/workflows/tests.yml
  Makefile
  app.json
  lumium-api/Cargo.lock
  lumium-api/Procfile
  lumium-space/package.json
  lumium-space/scripts/build-renderer.sh
  lumium-space/src/components/security/Authenticator.tsx
  package.json
  scripts/reduce-slug-size-heroku.sh
  scripts/toolchain.sh
  tsconfig.base.json
  yarn.lock
Labels: enhancement, infrastructure
